### ISSUE TITLE
Calling the AuthenticationContext TokenCache ReadItems method always returns 0 items and Count is changed to 0 after calling

### ISSUE THREAD

**Issue by ghost** [AzureAD/azure-activedirectory-library-for-dotnet#1611]
**Which Version of ADAL are you using ?**
5.0.5

**Which platform has the issue?**
iOS

**What authentication flow has the issue?**
* Desktop / Mobile
    * [ x] Broker

Other? - please describe;

**Is this a new or existing app?**
existing app 

**Repro**
var authContext = new AuthenticationContext(endpoint.Authority);
tokenCache = authContext.TokenCache.ReadItems();

**Expected behavior**
When looking at the authContext.TokenCache Count property - it clearly shows 1 item in cache for example.  I expect if I call ReadItems it would return that 1 item.  

**Actual behavior**
Anytime I call ReadItems the amount of items coming back is 0 and the count switches to 0

**Possible Solution**

**Additional context/ Logs / Screenshots**
This can be repo'd from the Reference App I have on github using the Azure Token Generator page and then the Azure Token Cache page.

https://github.com/biozal/Xamarin-Forms-Reference-App

**Comment by ghost** [comment]
@jennyf19 I'll add this behavior is only happening in iOS.  In Android the feature is functioning as it should.

**Comment by jennyf19** [comment]
Thanks, @biozal ...we're going to try and get an ADAL release out w/a few small fixes, so I'll probably have time to take a look at this. Just to clarify, is this w/using broker or without?

**Comment by ghost** [comment]
@jennyf19 I feel really bad now, you can close this issue.  I was using your test version of 5.01 when this was happening. I switched back to 5.0.5 for all our stuff today and it works on both platforms.  The issue was with broker, but given it's fixed in 5.0.5 I'm happy!

**Comment by jennyf19** [comment]
@biozal hooray...and great timing. I wonder what fixed it. So you're all good aside from the iOS broker issue -> ADAL.NET skipping keychain w/calls from broker due to lack of client_info returned from broker..?

**Comment by jennyf19** [comment]
Also, @biozal before we close this, I sent you our 5.0.6 release, if you want to verify the issue does not repro there, that would be great. thx.

**Comment by ghost** [comment]
Checking now!

**Comment by jennyf19** [comment]
fixed in [adal 5.1.0](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/releases/tag/5.1.0)

**Comment by amt-work** [comment]
I'm still having this issue, even after updating my adal to 5.1.0 in my PCL and ios project. Same steps, before the readitems is called the count shows 1, after is shows 0. My token doesn't appear to be saving in the cache. I noticed this issue is happening after I started integrating the intune MAM steps in my existing ADAL application. When I remove the line that sets the iOSKeychainSecurityGroup property to my bundle ID, the application can at least cache my token, but with that line it doesn't work. @jennyf19

**Comment by jennyf19** [comment]
@amt-work Which version of authenticator are you using? you need to have at least 6.3.6 or higher

**Comment by amt-work** [comment]
I'm not using authenticator, this is when providing credentials without having authenticator on your device. @jennyf19

**Comment by jennyf19** [comment]
@amt-work Thanks for the clarification...what do you mean by this " integrating the intune MAM steps in my existing ADAL application"?

**Comment by amt-work** [comment]
@jennyf19 Sorry about that, my xamarin app already uses ADAL to authenticate users with single sign on, giving them the option to log in with authenticator or by typing in their login info and using 2FA. This works well, but I want to now incorporate the intune SDK in my app as well, when doing that I noticed that by following the steps provided on the microsoft website after I added in the ioskeychainsecuritygroup property my app can no longer cache tokens.

**Comment by jennyf19** [comment]
@amt-work Can you share the link to the Microsoft site you're using w/the steps on how to do this? And confirming you're on the latest version of ADAL and you'll need the newest release of the Intune SDK (11.0.8). If that doesn't work for you, can you open a new issue here?

**Comment by amt-work** [comment]
@jennyf19 This is the link I'm following: https://docs.microsoft.com/en-us/intune/app-sdk-xamarin and yes I do have the latest release. I'll open a new issue now.
