### ISSUE TITLE
Can't reuse ClientCredential

### ISSUE THREAD

**Issue by craigb** [AzureAD/azure-activedirectory-library-for-dotnet#999]
I'm upgrading from v2 to v3, and I ran into a strange issue. The constructor for `ClientCredential` now needs an `ISecureClientSecret` instead of a `SecureString`. It seemed pretty innocuous to simply wrap my secure strings in a `SecureClientSecret` and chug along happily. I did this, and got null reference exceptions when trying to run my code. A quick search comes up with a [StackOverflow page](https://stackoverflow.com/questions/46959317/null-reference-exception-using-adal-for-acquiringtokenasync-with-resource-and-cl) that explains the issue. To recap, the `SecureClientSecret` clears the secure string and nulls out its reference to it upon the [first call to `ApplyTo()`](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/blob/62a82c78b2a8504065f342309f8015dde8b9eccc/adal/src/Microsoft.IdentityModel.Clients.ActiveDirectory/Platforms/net45/SecureClientSecret.cs#L78).

My particular problem is that `ClientCredential` used to be reusable, regardless of the secret delivery mechanism. The code I'm updating puts it in a Unity container for reuse. So, I'm looking to understand if we've been thinking about them improperly or if this is simply a bug. The `SecureClientSecret` has been around for about 2 years now, so I'm really not sure.

**Comment by jennyf19** [comment]
@craigb 
We changed the api surface in ADAL v3, which is a major version upgrade, from v2. Have you looked at our [documentation](https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/wiki/Client-credential-flows) on using `ISecureClientSecret`?

We clear out the secure string for security reasons.

**Comment by craigb** [comment]
I have looked at the documentation, but there's no mention of the ISecureClientSecret being an object that can only be used one time. The implication of this is that the ClientCredentials that are instantiated with one self-destruct after they are used once. So the lifetime of a ClientCredentials object is dependent on the constructor used to instantiate it, unless you have some other definition I haven't seen yet. In other words, how would you answer the question: Can I cache a ClientCredentials instance?

I'd like to educate myself more about the security reasons for nulling out the reference to the secure string. Can you point me to some documentation about the security reasons for doing this?

**Comment by jmprieur** [comment]
Fixed in #1087

**Comment by JacksReacher** [comment]
Has anyone verified this? I'm still getting errors related to this issue.

**Comment by jmprieur** [comment]
@joepeavey : we got positive verification from the AzureAD PowerShell team.
Did you update to the latest AzureAD powerShell module?

**Comment by JacksReacher** [comment]
I'm not using powershell, I'm using clientcredential in a Web App hosted in PF and it's still losing the password...

**Comment by jmprieur** [comment]
@joepeavey can you please share repro steps?

**Comment by jmprieur** [comment]
@joepeavey : closing this issue as we think it's fixed, and you have not provided repro steps. Feel free to reopen if you have the repro steps.
